# Basic Site Settings
locale: "en-US"
title: "Evariste / Webariste"
description: "I don't know what i am doing here."
url: https://evariste-git.github.io

markdown: kramdown

include:
  - _pages
exclude:
  - Gemfile
  - justfile
  - LICENSE
  - README
  - vendor
keep_files:
  - .git

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

# HTML Compression
# see https://jch.penibelst.de/ for more information
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development
  blanklines: false
  profile: false
